version: "3.7"

services:
  embedding_server:
    build: ./webservice/embedding_server
    container_name: embedding_server
    restart: always
    volumes:
      - ./resources/embeddings/embedding_query:/embedding_query
    expose:
      - 24805

  website_server:
    build: ./webservice/website_server
    container_name: website_server
    restart: always
    expose:
      - 24803

  approach_a:
    build: ./webservice/appA
    container_name: approach_a
    restart: always
    volumes:
      - ./resources/approach_a/data:/data
    expose:
      - 24801

  approach_b:
    build: ./webservice/appB
    container_name: approach_b
    restart: always
    expose:
      - 24802

  gerbil:
    build: ./gerbil
    container_name: gerbil
    restart: always
    expose:
      - 24804
    volumes:
      - evaluation:/evaluation

  nginx:
    build: ./webservice/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

volumes:
  evaluation: null
