version: "3.7"

services:
  embedding_server:
    build: ./embedding_server
    container_name: embedding_server
    restart: always
    expose:
      - 24805

  website_server:
    build: ./website_server
    container_name: website_server
    restart: always
    expose:
      - 24803

  approach_a:
    build: ./appA
    container_name: approach_a
    restart: always
    expose:
      - 24801

  approach_b:
    build: ./appB
    container_name: approach_b
    restart: always
    expose:
      - 24802

  gerbil:
    build: ./gerbil
    container_name: gerbil
    restart: always
    expose:
      - 24804

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
