default_language_version:
  node: 16.14.2
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        name: Prettier - format code of web development files

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        name: pyupgrade - upgrade syntax for newer python versions

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black - format python code

  - repo: https://github.com/sqlalchemyorg/zimports
    rev: v0.6.0
    hooks:
      - id: zimports
        name: zimports - reformat python imports

  - repo: https://github.com/PyCQA/pylint
    rev: v2.13.9
    hooks:
      - id: pylint
        name: Pylint - check for errors in Python code
        exclude: (?x)^(KBQA/kbqa/ | KBQA/appB/transformer_architectures/kb/)
        additional_dependencies:
          [
            rdflib==6.0.2,
            requests==2.26.0,
            flask==2.0.2,
            numpy==1.21.3,
            SPARQLWrapper==1.8.5,
          ]
      - id: pylint
        name: Pylint (appA)
        files: ^KBQA/kbqa/webservice/appA/
        additional_dependencies:
          [
            flask==2.0.2,
            requests==2.26.0,
            SPARQLWrapper==1.8.5,
            transformers==4.5.1,
            spacy_dbpedia_spotlight==0.2.2,
          ]
      - id: pylint
        name: Pylint (appB)
        files: ^KBQA/kbqa/webservice/appB/
        additional_dependencies:
          [flask==2.0.2, requests==2.26.0, SPARQLWrapper==1.8.5]
      - id: pylint
        name: Pylint (website_server)
        files: ^KBQA/kbqa/webservice/website_server/
        additional_dependencies: [flask==2.0.2, requests==2.26.0]
      - id: pylint
        name: Pylint (gerbil)
        files: ^KBQA/kbqa/webservice/gerbil/
        additional_dependencies:
          [flask==2.0.2, requests==2.26.0, pandas, simplejson]
      - id: pylint
        name: Pylint (embedding_server)
        files: ^KBQA/kbqa/webservice/embedding_server/
        additional_dependencies: [flask==2.0.2, requests==2.26.0, numpy==1.21.3]
      - id: pylint
        name: Pylint (kb)
        files: ^KBQA/appB/transformer_architectures/kb/
        additional_dependencies:
          [
            torch==1.11.0,
            pytorch-pretrained-bert==0.6.2,
            transformers==4.17.0,
            spacy==3.2.3,
            allennlp==2.9.2,
            scipy==1.8.0,
            rdflib==6.1.1,
            overrides==6.1.0,
          ]
        args: ["--rcfile=/home/jmenzel/Documents/custom.rc"]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: Flake8 - check python source files for errors and style

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        name: Mypy - check python static types
        exclude: ^KBQA/kbqa/
        additional_dependencies: [types-requests]
      - id: mypy
        name: mypy (appA)
        files: ^KBQA/kbqa/webservice/appA/
        additional_dependencies: [types-requests]
      - id: mypy
        name: mypy (appB)
        files: ^KBQA/kbqa/webservice/appB/
        additional_dependencies: [types-requests]
      - id: mypy
        name: mypy (website_server)
        files: ^KBQA/kbqa/webservice/website_server/
        additional_dependencies: [types-requests]
      - id: mypy
        name: mypy (gerbil)
        files: ^KBQA/kbqa/webservice/gerbil/
        additional_dependencies: [types-requests, types-simplejson]
      - id: mypy
        name: mypy (embedding_server)
        files: ^KBQA/kbqa/webservice/embedding_server/
        additional_dependencies: [types-requests]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        name: pydocstyle - check compliance with python docstring conventions

exclude: |
  (?x)^(
    KBQA/appB/transformer_architectures/BERT_WordPiece_SPBERT/. |
    KBQA/appB/preprocessing/. |
    KBQA/appB/transformer_architectures/bert_spbert_spbert_base/. |
    KBQA/appB/transformer_architectures/bert_spbert_spbert/. |
    KBQA/kbqa/webservice/appA/app/nspm/generator_utils.py |
    KBQA/kbqa/webservice/appB/app/bert_wordpiece_spbert/ |
    KBQA/tests/
  )

ci:
  autoupdate_branch: "develop"
  skip: [pylint, flake8, mypy, pydocstyle]
