version: "3.9"

services:
  reverseproxy:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
