"""Arguments for all KnowBert-SPBert-SPBert."""
from types import SimpleNamespace


KNOWBERT_SPBERT_SPBERT = SimpleNamespace(
    **{
        "encoder_model_name_or_path": "bert-base-cased",
        "decoder_model_name_or_path": "razent/spbert-mlm-wso-base",
        "knowbert_batchifier_config_path": "https://allennlp.s3-us-west-2.amazonaws.com/knowbert/models/knowbert_wiki_wordnet_model.tar.gz",
        "load_model_checkpoint": "Yes",
        "load_model_path": "/models/pytorch_model.bin",
        "model_type": "bert",
        "model_architecture": "bert2bert",
        "output_dir": "app/output/",
        "train_filename": None,
        "dev_filename": None,
        "test_filename": None,
        "predict_filename": "app/data/output/question",
        "source": "en",
        "target": "sparql",
        "config_name": "",
        "tokenizer_name": "",
        "max_source_length": 32,
        "max_triples_length": 512,
        "max_target_length": 192,
        "do_train": False,
        "do_eval": False,
        "do_test": False,
        "do_predict": True,
        "do_lower_case": False,
        "no_cuda": True,
        "train_batch_size": 1,
        "eval_batch_size": 1,
        "gradient_accumulation_steps": 1,
        "learning_rate": 5e-5,
        "beam_size": 10,
        "weight_decay": 0.0,
        "adam_epsilon": 1e-8,
        "max_grad_norm": 1.0,
        "num_train_epochs": 3,
        "max_steps": -1,
        "eval_steps": -1,
        "train_steps": -1,
        "warmup_steps": 0,
        "local_rank": -1,
        "seed": 42,
        "save_interval": 1,
        "uncased_NL": True,
    }
)