name: Testing

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Get new version
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.0.0

      - name: Run linters
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: -v --hook-stage push --files ${{ steps.changed-files.outputs.all_changed_files }}
          token: ${{ secrets.github_token }}
